### ISSUE TITLE
Select multiple links at once to copy title and/or URL

### ISSUE THREAD

**Issue by Bamajon1974** [igorlogius/copy-link-extras#1]
Good afternoon

Thank you for publishing this useful extension. 

Is it possible to select multiple links at once to copy the title and/or URL's at once? If not, could this option be added? 

Thanks!

**Comment by Bamajon1974** [comment]
Great! Thank you! Please keep me posted!

**Comment by Bamajon1974** [comment]
Just to help you out...this extension has the ability to copy multiple links to the clipboard. I think you can even copy the title as well but it would be nice to have the ability to copy a title, URL, title + URL on the same line and title + URL on different lines. Does that make sense? 
https://addons.mozilla.org/en-US/firefox/addon/copy-selected-links/

**Comment by igorlogius** [comment]
That uses the mentioned browser built-in selection, which i guess is fine for selecting everything that is inside of one big block ... i'll see what i can do.

**Comment by igorlogius** [comment]
Added to version 1.1.3

https://github.com/igorlogius/copy-link-extras/assets/67047467/d525a8e1-4c47-4742-a15f-fce90289589b

**Comment by Bamajon1974** [comment]
"That uses the mentioned browser built-in selection, which i guess is fine for selecting everything that is inside of one big block ... i'll see what i can do." 

Correct. What was the other method you were referring to?

**Comment by Bamajon1974** [comment]
Oh wow, that was fast. I will try out the new version tomorrow. Thank you!

**Comment by igorlogius** [comment]
> What was the other method you were referring to?

Let's just say ... that method would be a lot more work to add and likely even more error prone with the only potential benefit of maybe having a better UI. So you can just ignore i said anything if the built-in method works for you. :wink:

**Comment by Bamajon1974** [comment]
I loaded the extension into Firefox and works perfectly. Thank you very much. Do you have a Patreon or other account to contribute to your time and effort?

Also, I have another question about an unrelated feature. Where is a good place to ask?

**Comment by igorlogius** [comment]
> I loaded the extension into Firefox and works perfectly. Thank you very much. 

That is nice to hear. 

> Do you have a Patreon or other account to contribute to your time and effort?

I only have a bitcoin wallet (address: 35WK2GqZHPutywCdbHKa9BQ52GND3Pd6h4 ) as a tip jar where you can drop a satochi or two if you like.

> Also, I have another question about an unrelated feature. Where is a good place to ask?

If it is unrelated to this issue, but relates to this addon then you can just open another issue in this repo, but if you mean that it is unrelated to this or any other existing addon then you can just open an issue here: https://github.com/igorlogius/not-on-amo/issues

Hope it helps. Later.

**Comment by Bamajon1974** [comment]
Please forgive my ignorance, but I have never tipped using bitcoin. Is there a way to send a tip to your bitcoin wallet from Venmo or PayPal? 

Question is somewhat unrelated. I will ask on the provided link.

**Comment by igorlogius** [comment]
> Is there a way to send a tip to your bitcoin wallet from Venmo or PayPal?

I dont use either of those services so i dont know for sure ... but searching for "sending crypto via ..."  i found these

- https://help.venmo.com/hc/en-us/articles/16145303480595-Crypto-Transfers-
- https://newsroom.paypal-corp.com/2022-06-07-PayPal-Users-Can-Now-Transfer-Send-and-Receive-Bitcoin-Ethereum-Bitcoin-Cash-and-Litecoin

So maybe? If it's to much of a hassel, just dont bother. It's really not a big deal.

**Comment by Bamajon1974** [comment]
Thank you and no hassle at all. I have never bought bitcoin or left a tip or paid anything with bitcoin before so let me read up on it first.

**Comment by Bamajon1974** [comment]
I figured out the tipjar. I have to buy bitcoin from PayPal or Venmo and let it clear before transferring anything out. Should take a day or so. I will leave you a nice tip for helping solve some workflow problems with your extensions.

**Comment by igorlogius** [comment]
Thank you. 

Hope you get some good usage out of the extension and let me know if you find any bugs that need patching. 

Have a nice day and see you around.

**Comment by Bamajon1974** [comment]
Good evening. I think I finally figured out the bitcoin issue. This has been quite the journey. Anyway, I sent a couple of bucks to test to your wallet, 35WK2GqZHPutywCdbHKa9BQ52GND3Pd6h4. Can you confirm receipt?

**Comment by igorlogius** [comment]
Yep i can confirm the receipt. The tip arrived safe and sound. 

Thanks again!

**Comment by Bamajon1974** [comment]
Great. I will send some more shortly...because both extensions have really helped out my workflow productivity. I just wanted to make sure a small tip arrived first before sending the rest.

**Comment by igorlogius** [comment]
> just wanted to make sure a small tip arrived first before sending the rest.

Smart move.

**Comment by Bamajon1974** [comment]
Ok I sent the rest of the tip. Did you receive?

**Comment by igorlogius** [comment]
> Ok I sent the rest of the tip. Did you receive?

yep, got it. Thanks!

**Comment by Bamajon1974** [comment]
Very welcome!
