### ISSUE TITLE
PayPal cash  Generator 

### ISSUE THREAD

**Issue by Rebelman24** [igorlogius/copy-link-extras#2]
Wont let me in the generator to send myself 100 gift card pay pal

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by igorlogius** [comment]
> Wont let me in the generator to send myself 100 gift card pay pal

@Rebelman24 

To be frank, i dont understand how this has anything todo with the addon, so firstly i would request for you expand your description and and provide a bit more context. (How does you not being able to send yourself 100 gift card relate to the addon?)  
 
After you've dont that i'll gladly try to help out.
