### ISSUE TITLE
Copy Text Removes letter S

### ISSUE THREAD

**Issue by Bamajon1974** [igorlogius/copy-link-extras#3]
**Describe the bug**
I found a bug in the updated version of Copy Link Extras. When copying the text of several links at once, some of the letters "s" are removed. Please see the 

**To Reproduce**
Went to Amazon.com, selected all of the links at bottom from Getting to Know Us heading. 
Copied text and Text+URLs of all links in column
Pasted into Notepad3, WordPad, and msword
Restarted Firefox. Disabled and re-enabled extension
Tried on other websites like ESPN (couldn't reproduce), USAtoday (missing S) and Abcnews (missing S). 

**Expected behavior**
Letter S should not be omitted

**Screenshots**
Screenshot below

**Desktop (please complete the following information):**
Windows 10 22H2
Firefox 121

![copy](https://github.com/igorlogius/copy-link-extras/assets/48393602/c708f629-2cb3-4b2b-a7b0-7d54bdf9ba22)

**Comment by igorlogius** [comment]
I'll check.

**Comment by igorlogius** [comment]
Should be fixed in version `1.1.4`

**Comment by Bamajon1974** [comment]
Fixed. Thank you very much!
