### ISSUE TITLE
How to avoid line breaks when copying multiple links

### ISSUE THREAD

**Issue by RWY28** [igorlogius/copy-link-extras#4]
Hi,

I've added Copy Link Extras to my FF browser, it's really great, congrats!

However, when it comes to own new rules, I'm missing a syntax description.
For example, I want to avoid line breaks when copying multiple links from a website, extracting the link labels only.

Could you please give a hint or some examples to achieve that?

Thank you in advance!

Best regards,
Andreas Rau

**Comment by igorlogius** [comment]
Not sure if i understand you exactly, but try entering a single  space into the `Seperator` input field on the Preference page. 

If that is not what you want you might have to explain it to me via an example.

**Comment by RWY28** [comment]
Yes, it’s exactly what I was asking for, thank you!

I simply didn’t know how to use the Separator field.

Best regards
Andreas

**Comment by igorlogius** [comment]
Glad to help out. :+1:
